### ISSUE TITLE
Don't works with ember 2.11

### ISSUE THREAD

**Issue by villander** [rmmmp/ember-firebase-service#3]
````
ember-cli: 2.11.1
node: 6.9.2
os: darwin x64

vzon-web git:(feature/android-notification) ✗ ember s
Livereload server on http://localhost:49153
Serving on http://localhost:4200/
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (vendor & appJS)] failed with:
Error: ENOENT: no such file or directory, open '/Users/flama/Projects/vzon-web/tmp/source_map_concat-input_base_path-NQYmV0IK.tmp/node_modules/firebase/firebase.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at SourceMap.addFile (/Users/flama/Projects/vzon-web/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
    at /Users/flama/Projects/vzon-web/node_modules/broccoli-concat/concat.js:200:16
    at Array.forEach (native)
    at Concat.<anonymous> (/Users/flama/Projects/vzon-web/node_modules/broccoli-concat/concat.js:198:24)
    at /Users/flama/Projects/vzon-web/node_modules/fast-sourcemap-concat/lib/source-map.js:419:12
    at initializePromise (/Users/flama/Projects/vzon-web/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/Users/flama/Projects/vzon-web/node_modules/rsvp/dist/rsvp.js:1039:33)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Users/flama/Projects/vzon-web/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/flama/Projects/vzon-web/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/Users/flama/Projects/vzon-web/node_modules/broccoli-merge-trees/index.js:36:53)
    at mergeTrees (/Users/flama/Projects/vzon-web/node_modules/ember-cli/lib/broccoli/merge-trees.js:46:18)
    at EmberApp.javascript (/Users/flama/Projects/vzon-web/node_modules/ember-cli/lib/broccoli/ember-app.js:1306:10)
    at EmberApp.toArray (/Users/flama/Projects/vzon-web/node_modules/ember-cli/lib/broccoli/ember-app.js:1674:10)
    at EmberApp.toTree (/Users/flama/Projects/vzon-web/node_modules/ember-cli/lib/broccoli/ember-app.js:1696:30)
    at module.exports (/Users/flama/Projects/vzon-web/ember-cli-build.js:73:14)
    at CoreObject.setupBroccoliBuilder (/Users/flama/Projects/vzon-web/node_modules/ember-cli/lib/models/builder.js:84:19)
    at CoreObject.init (/Users/flama/Projects/vzon-web/node_modules/ember-cli/lib/models/builder.js:64:10)


cleaning up...
```

**Comment by rmmmp** [comment]
Can't look at it right now but is there any chance you're also using emberfire? That's going to cause a conflict.

**Comment by villander** [comment]
No! I don't use emberfire

**Comment by villander** [comment]
No. I don't use emberfire

**Comment by villander** [comment]
👀

**Comment by rmmmp** [comment]
I haven't had the time to look into it yet although I could see that I'm using a new [API](https://emberjs.com/blog/2017/09/01/ember-2-15-released.html#toc_app-import-files-within-node_modules) from Ember CLI 2.15. This might be what's causing the issue.

**Comment by rmmmp** [comment]
Ember CLI 2.11 is no longer supported as this addon follows the Ember LTS lifecycle which makes 2.12 the last one to support.
